use std::{fs, path::PathBuf};

use quote::quote;
use xsd_parser::{
    Config, IdentType,
    config::{
        Generate, GeneratorFlags, IdentQuadruple, InterpreterFlags, OptimizerFlags, ParserFlags,
        Resolver, Schema,
    },
    generate,
    models::meta::{CustomMeta, MetaType},
    pipeline::{
        generator::{Context as GeneratorContext, Error as GeneratorError, ValueGeneratorMode},
        renderer::{NamespaceSerialization, ValueRendererBox},
    },
};

fn main() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let output = manifest_dir.join("src/generated.rs");

    let mut config = Config::default()
        .with_derive(["Debug", "Clone"])
        .with_schema(Schema::File(manifest_dir.join("SpaceSystem.xsd")))
        .with_quick_xml_config(NamespaceSerialization::Global, None, true)
        .with_parser_flags(ParserFlags::all())
        .with_interpreter_flags(InterpreterFlags::all())
        .with_optimizer_flags(OptimizerFlags::all() - OptimizerFlags::REMOVE_DUPLICATES)
        .with_generator_flags(
            GeneratorFlags::all()
                - GeneratorFlags::ADVANCED_ENUMS
                - GeneratorFlags::USE_MODULES
                - GeneratorFlags::NILLABLE_TYPE_SUPPORT,
        );
    config.parser.resolver = vec![Resolver::File, Resolver::Web];
    config.generator.generate = Generate::Types(vec![IdentQuadruple::from((
        IdentType::Element,
        "xtce:SpaceSystem",
    ))]);
    config.interpreter.types = ["ComparisonOperatorsType", "MathOperatorsType"]
        .into_iter()
        .map(|name| {
            (
                IdentQuadruple::from((IdentType::Type, format!("xtce:{name}"))),
                MetaType::from(CustomMeta::new("OperatorString").with_default(
                    |ctx: &GeneratorContext<'_, '_>,
                     value: &str,
                     mode: ValueGeneratorMode|
                     -> Result<ValueRendererBox, GeneratorError> {
                        if mode != ValueGeneratorMode::Value {
                            return Err(GeneratorError::InvalidDefaultValue {
                                ident: ctx.ident.clone(),
                                value: value.into(),
                                mode,
                            });
                        }

                        Ok(Box::new(quote! {
                            ::std::string::String::from(#value)
                        }))
                    },
                )),
            )
        })
        .collect();

    let tokens = generate(config).expect("failed to generate XTCE 1.3 bindings");
    let syntax = syn::parse2(tokens).expect("generated invalid Rust syntax");
    let source = format!(
        "// @generated by `cargo run -p xtce --example generate`; do not edit.\n\n{}",
        prettyplease::unparse(&syntax)
    );

    fs::write(&output, source).expect("failed to write src/generated.rs");
    println!("generated {}", output.display());
}
