[package]
name = "xtce-editor"
version = "0.1.0"
edition = "2024"

[dependencies]
xtce = { path = "../xtce" }

anyhow = "1.0.104"
gpui = { git = "https://github.com/zed-industries/zed" }
gpui_platform = { git = "https://github.com/zed-industries/zed", features = ["font-kit", "wayland", "x11",] }
gpui-component = { git = "https://github.com/longbridge/gpui-component" }
gpui-component-assets = { git = "https://github.com/longbridge/gpui-component" }
lsp-types = "0.97.0"
strum = { version = "0.27.2", features = ["derive"] }
